services:
  web:
    image: nginx:1.27.5-alpine
    ports:
      - "8080:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./pages:/app/pages
      - ./videos:/app/videos
    ports:
      - "1323:1323"
    depends_on:
      - db
  db:
    image: mysql:9.3
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo