services:
  web:
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./pages:/www/data/html
      - ./contents/videos/encoded:/www/data/videos
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./contents/videos/original:/data/videos
    ports:
      - "${API_PORT}:1323"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MQ_HOST: ${RABBITMQ_HOST}
      MQ_PORT: ${RABBITMQ_PORT}
      MQ_USER: ${RABBITMQ_USER}
      MQ_PASS: ${RABBITMQ_PASS}
      QUEUE_NAME: ${QUEUE_NAME}
  encoder:
    build:
      context: ./encoder
      dockerfile: Dockerfile
    volumes:
      - ./encoder:/app
      - ./contents/videos/original:/data/videos/original
      - ./contents/videos/encoded:/data/videos/encoded
    depends_on:
      - api
      - rabbitmq
    environment:
      MQ_HOST: ${RABBITMQ_HOST}
      MQ_PORT: ${RABBITMQ_PORT}
      MQ_USER: ${RABBITMQ_USER}
      MQ_PASS: ${RABBITMQ_PASS}
      QUEUE_NAME: ${QUEUE_NAME}
  db:
    image: mysql:9.3
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
  rabbitmq:
    image: rabbitmq:4.1.0-management
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGER_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      