services:
  web:
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./pages:/www/data/html
      - ./videos:/www/data/videos
    ports:
      - "8080:80"
    depends_on:
      - api
      - db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./videos:/app/videos
    ports:
      - "1323:1323"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.3
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  rabbitmq:
    image: rabbitmq:4.1.0-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password